# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e8dd1ac80c4b1b7171dc1bc0a891ebcf196f8ce5b9b99a1f00b850b66d6308e6f9236ec69f8a9c2830735b91b0dd44ef7a2fa8696405277d2d3e9df39b935b2

test:
  secret_key_base: db39f86c78f9950d1a90df17c81e1f67bcce0157b9dcf1d919c0b43858d85e86832d4ed507ff0d7d5ce3b80764266ffad2db5587d54780c9fa68465a51312c82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
